MODEL:
  NUM_CLASSES: 700
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5

  # multi-dataset options
  USE_MULTI_HEAD: True
  MULTI_DATASETS: ["kinetics", "mit", "ssv2"]
  MULTI_REPLICAS: [1, 1, 1]
  MULTI_LOSS_FUNCS: ["soft_cross_entropy", "soft_cross_entropy", "soft_cross_entropy"]
  MULTI_NUM_CLASSES: [400, 305, 174]
  MULTI_HEAD_ACT: ["softmax", "softmax", "softmax"]
  MULTI_LOSS_WEIGHTS: [1, 1, 1]

  # path to each dataset annotation and videos
  # need to be the same order as above
  MULTI_PATH_TO_DATA_DIR: [
      "/data_nvme/datasets/kinetics400/pyslowfast_annotations",
      "/data_nvme/datasets/moments_in_time/pyslowfast_annotations",
      "/data_nvme/datasets/ssv2/pyslowfast_annotations",
  ]
  MULTI_PATH_PREFIX: [
      "/data_nvme/datasets/kinetics400/videos_320p",
      "/data_nvme/datasets/moments_in_time/videos_320p",
      "/data_nvme/datasets/ssv2/videos_320p",
  ]
  MULTI_ADD_CROSS_PROJ: True
  MULTI_CROSS_PROJ_ADD_TO_PRED: False
  USE_INF_LOSS: True
  USE_INF_EXPANDER: True
  USE_INF_LEARN_WEIGHT: False
  INF_LOSS_WEIGHT: 0.1
  MULTI_USE_MLP: True
  MULTI_USE_MTL_WEIGHT: False
  MULTI_PROJ_LOSS_WEIGHT: 1.0
  MULTI_PROJ_LOSS_FUNC: "soft_cross_entropy"
  MULTI_PROJ_SPARSITY_LOSS_TYPE: ""
  LOAD_MULTI_PROJ_INIT_FILE: ""

TRAIN:
  ENABLE: True
  GATHER_BEFORE_LOSS: True
  DATASET: multi_dataset_seq
  BATCH_SIZE: 64
  GRAD_ACCU_NUM_BATCH: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: decord
  NUM_FRAMES: 32
  SAMPLING_RATE: 3
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-k400-dir
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  # needed for multi-dataset training
  MULTI_LABEL: True
  VAL_SKIP: 5
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 24
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.1
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[2, 1, 2, 2], [5, 1, 2, 2], [21, 1, 2, 2]]
  DROPOUT_RATE: 0.0
  # MVIT version 2 by junwei
  CHANNEL_EXPAND_FRONT: True
  Q_POOL_ALL: True
  Q_POOL_RESIDUAL: True
AUG:
  ENABLE: True
  NUM_SAMPLE: 2
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0002
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 0.000002
  WARMUP_START_LR: 0.000002
  WARMUP_EPOCHS: 10.0
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
